# Generated by Django 5.2.7 on 2026-02-28 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('source', models.CharField(max_length=50, verbose_name='Источник API')),
                ('status', models.CharField(max_length=20, verbose_name='Статус запроса')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Ответ API')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог запроса API',
                'verbose_name_plural': 'Логи запросов API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='ИНН')),
                ('company_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название компании')),
                ('legal_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Юридическое название')),
                ('legal_form', models.CharField(blank=True, max_length=50, null=True, verbose_name='Форма организации')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('okpo', models.CharField(blank=True, max_length=10, null=True, verbose_name='ОКПО')),
                ('okved', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОКВЭД')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('address_full', models.TextField(blank=True, null=True, verbose_name='Полный адрес')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс')),
                ('director_fio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Генеральный директор')),
                ('director_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность руководителя')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('authorized_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Уставный капитал')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Выручка')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Прибыль')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('liquidation_date', models.DateField(blank=True, null=True, verbose_name='Дата ликвидации')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Сырые данные API')),
                ('source', models.CharField(default='checko', max_length=50, verbose_name='Источник данных')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуальные данные')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Запросил')),
            ],
            options={
                'verbose_name': 'Данные компании',
                'verbose_name_plural': 'Данные компаний',
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('excel', 'Excel файл'), ('pdf', 'PDF файл'), ('scan', 'Скан документа'), ('other', 'Другой документ')], max_length=50, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='company_documents/%Y/%m/%d/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.companydata', verbose_name='Компания')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_documents', to='crm.lead', verbose_name='Лид')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ компании',
                'verbose_name_plural': 'Документы компаний',
            },
        ),
        migrations.CreateModel(
            name='CompanyLeadRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата связи')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companydata', verbose_name='Компания')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'Связь компании с лидом',
                'verbose_name_plural': 'Связи компаний с лидами',
                'unique_together': {('company', 'lead')},
            },
        ),
        migrations.AddField(
            model_name='companydata',
            name='leads',
            field=models.ManyToManyField(related_name='company_data', through='companies.CompanyLeadRelation', to='crm.lead', verbose_name='Связанные лиды'),
        ),
        migrations.AddIndex(
            model_name='companydata',
            index=models.Index(fields=['inn'], name='companies_c_inn_7c48fb_idx'),
        ),
        migrations.AddIndex(
            model_name='companydata',
            index=models.Index(fields=['company_name'], name='companies_c_company_dd7940_idx'),
        ),
        migrations.AddIndex(
            model_name='companydata',
            index=models.Index(fields=['legal_name'], name='companies_c_legal_n_0d1f8e_idx'),
        ),
    ]
