# Generated by Django 5.2.7 on 2026-02-28 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_columns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма сделки')),
                ('inn', models.CharField(blank=True, max_length=12, null=True)),
                ('ogrn', models.CharField(blank=True, max_length=13, null=True)),
                ('director_fio', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('legal_form', models.CharField(blank=True, max_length=20, null=True, verbose_name='Форма организации')),
                ('legal_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Юридическое название')),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Контактный телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Контактный email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('partner_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Партнёр (ФИО)')),
                ('partner_position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность партнёра')),
                ('partner_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон партнёра')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник')),
                ('priority', models.CharField(choices=[('not_set', 'Не обозначен'), ('low', 'Низкий'), ('high', 'Высокий'), ('critical', 'Критический')], default='not_set', max_length=20, verbose_name='Приоритет')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.kanbancolumn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LeadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lead_files/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_inn', models.BooleanField(default=True)),
                ('show_partner', models.BooleanField(default=False)),
                ('show_amount', models.BooleanField(default=True)),
                ('show_contact_person', models.BooleanField(default=True)),
                ('show_phone', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=True)),
                ('show_city', models.BooleanField(default=True)),
                ('show_source', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
