# Generated by Django 5.2.7 on 2026-02-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_address',
            field=models.BooleanField(default=False, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_bank_name',
            field=models.BooleanField(default=True, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_comment',
            field=models.BooleanField(default=False, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_created_at',
            field=models.BooleanField(default=False, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_credit_purpose',
            field=models.BooleanField(default=True, verbose_name='Цель кредита'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_credit_term',
            field=models.BooleanField(default=True, verbose_name='Срок кредита'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_director',
            field=models.BooleanField(default=False, verbose_name='Директор'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_legal_form',
            field=models.BooleanField(default=False, verbose_name='Орг. форма'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_legal_name',
            field=models.BooleanField(default=False, verbose_name='Юр. название'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_next_call',
            field=models.BooleanField(default=False, verbose_name='След. звонок'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_ogrn',
            field=models.BooleanField(default=False, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_status',
            field=models.BooleanField(default=True, verbose_name='Статус заявки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_website',
            field=models.BooleanField(default=False, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_amount',
            field=models.BooleanField(default=True, verbose_name='Сумма сделки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_city',
            field=models.BooleanField(default=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_contact_person',
            field=models.BooleanField(default=True, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_inn',
            field=models.BooleanField(default=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_partner',
            field=models.BooleanField(default=False, verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_phone',
            field=models.BooleanField(default=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_source',
            field=models.BooleanField(default=False, verbose_name='Источник'),
        ),
    ]
