# Generated by Django 5.2.7 on 2025-12-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('normal', 'Обычный'), ('low', 'Низкий'), ('high', 'Высокий'), ('critical', 'Критический')], default='normal', max_length=20, verbose_name='Приоритет'),
        ),
    ]
