# Generated by Django 5.2.7 on 2025-12-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_lead_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('not_set', 'Не обозначен'), ('low', 'Низкий'), ('high', 'Высокий'), ('critical', 'Критический')], default='not_set', max_length=20, verbose_name='Приоритет'),
        ),
    ]
