# Generated by Django 5.2.7 on 2026-02-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_profile_show_address_profile_show_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_bank_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_comment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_credit_purpose',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_credit_term',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_director',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_legal_form',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_legal_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_next_call',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_ogrn',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_website',
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_amount',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_city',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_contact_person',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_inn',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_source',
            field=models.BooleanField(default=False),
        ),
    ]
