# Generated by Django 5.2.7 on 2026-02-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_profile_show_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Сумма сделки'),
        ),
    ]
